Upd initramfs scripts (Support .squashfs names with spaces)
Re-write code for mount modules
Support .squashfs names with spaces

diff --git a/trixie/rootcopy/opt/initramfs/finit b/trixie/rootcopy/opt/initramfs/finit
--- a/trixie/rootcopy/opt/initramfs/finit
+++ b/trixie/rootcopy/opt/initramfs/finit
@@ -196,128 +196,27 @@ is_writable() { touch $1/.test 2>/dev/null; [ -e $1/.test ] && rm $1/.test; }
 # Failed to initiate changes. Creating temporary changes on tmpfs for this session.
 fail_chn() { mount -t tmpfs -o size=$RAMSIZE tmpfs /memory/changes; CHANGES=memory; CHNDEV=memory; touch /etc/nochanges; }
 
-# Just draw a line
-draw() { echo "${YELLOW}---------------------------------------------------------${RST}"; }
-
-# Copy modules
-cpmod() {
-NUM=`grep -c '.' $1`
-modfile=$1
-while read x; do
-    echo -en "${YELLOW}  ($NUM modules left)  ${RST} \r"; let NUM=NUM-1; NAME=`basename "$x"`
-    cp "$x" /memory/copy2ram 2>/dev/null
-    if [ $? -eq 0 ]; then
-	sed -i s@^.*/$NAME@/memory/copy2ram/$NAME@ /tmp/modules
-    else
-	rm /memory/copy2ram/"$NAME"
-	echo -e "${i}${CYAN}Not enough memory to copy ${NAME}${RST}"
-	echo -e "${i}${CYAN}Other modules will be skipped.${RST}"
-	find /memory/copy2ram -name "*.kmodsfs" | sort >/tmp/modules
-	find /memory/copy2ram -name "*.squashfs" | sort >>/tmp/modules
-	break
-    fi
-done < $modfile
-echo -en "                       \r"
+clean_changes_dir() {
+local U=$UPPERDIR
+rm -rf $U/dev $U/media $U/mnt $U/proc $U/run $U/sys $U/tmp 2>/dev/null
+rm -rf $U/var/lock/* $U/var/run $U/var/tmp $U/var/spool/cron/cron.?????? 2>/dev/null
+mkdir -p $UPPERDIR/mnt/live $WORKDIR
 }
 
-# If bootlog cheatcode is present then make log entry
-blog(){
-		param log && echo "$1" >> $LOGFILE
-}
-
-#======================================
-# setClean
-#--------------------------------------
-setClean()
-{
-[ $PFULL ] && UDIR=filesystem || UDIR=upperdir
-#=== 変分反映層
-	mkdir -p /memory/changes/$UDIR
-#=== 変分管理データ層
-	mkdir -p /memory/changes/workdir
-
-#--<継承エリア初期化>--#
-local PLACE=/memory/changes/$UDIR
-#	rm -rf $PLACE/boot 2>/dev/null
-	rm -rf $PLACE/dev 2>/dev/null
-	rm -rf $PLACE/mnt 2>/dev/null
-	rm -rf $PLACE/proc 2>/dev/null
-	rm -rf $PLACE/run 2>/dev/null
-	rm -rf $PLACE/sys 2>/dev/null
-	rm -rf $PLACE/tmp 2>/dev/null
-	rm -rf $PLACE/var/lock/* 2>/dev/null
-	rm -rf $PLACE/var/run 2>/dev/null
-	rm -rf $PLACE/var/tmp 2>/dev/null
-	rm -rf $PLACE/var/spool/cron/cron.?????? 2>/dev/null
-}
-#======================================
-# IncludeModules
-#--------------------------------------
-IncludeModules()
-{
-[ $PFULL ] && UDIR=filesystem || UDIR=upperdir
-echo yes > /etc/pfull-compat
-#=== 変分反映層
-mkdir -p /memory/changes/$UDIR
-UPPERDIR=/memory/changes/$UDIR
-#=== 変分管理データ層
-mkdir -p /memory/changes/workdir
-WORKDIR=/memory/changes/workdir
-
-#--<継承エリア初期化>--#
-setClean
-
-#=== 固定不変層
-LOWLIST=""
-a=2
-for x in `cat /tmp/modules`;
-do
-    ############### truncate mountpoint names ############## fred181 mod 231020 for 01-filesystem.squashfs
-    #   NAME=`basename $x`; //ORIGINAL line
-    if [ "$(basename $x)" = "01-filesystem.squashfs" ]; then  #fred181 mod 231020 keep name 01-filesystem.squashfs
-if [ $PFULL ] && [ -d /mnt/$DEV/$LPTH/pfull ]; then
-continue
+# Mount module
+mount_module() {
+# NUM+1 if /memory/images/$NAME exists already
+if [ -d /memory/images/"$NAME" ]; then let NUM=NUM+1
+	NAME="${NAME}-${NUM}"
+fi
+mkdir -p /memory/images/"$NAME"
+mount -o loop "$MODULE" /memory/images/"$NAME" 2>/dev/null
+if [ $? -eq 0 ]; then
+	echo -n " ${m} "; basename "$MODULE"
+	[ "$NAME" != "01-filesystem.squashfs" ] && echo "/memory/images/$NAME" >>/tmp/lowerdir
 else
-NAME=`basename $x`;
-fi
-	else
-        NAME=`basename ${x%.*}`; # remove extension .squashfs
-        #NAME="${NAME:0:14}""-$a" # initial OK 
-        #NAME="${NAME:0:14}""-$a"".squashfs" fix PROBLEM returned too many filename characters
-        NAME="${NAME:0:9}""-$a"".squashfs"
-	    # skip if (truncated) /memory/images/$NAME exists already
-	    [ -d /memory/images/$NAME ] && continue
-	    let a=a+1
- 	fi
-    #########################################################
-	mkdir /memory/images/$NAME;
-	mount -o loop $x /memory/images/$NAME 2>/dev/null
-	if [ $? -eq 0 ];
-	then
-		echo " ${m} `basename $x`"
-		LOWLIST=/memory/images/${NAME}:${LOWLIST}
-	else
-		echo "${i}${CYAN}Cannot read $NAME - corrupted module?${RST}"
-		rmdir /memory/images/$NAME
-	fi
-done
-if [ -z "$(echo "${LOWLIST}" | grep 01-filesystem.squashfs)" ]; then
-mkdir -p "/memory/images/01-filesystem.squashfs"
-LOWLIST=/memory/images/01-filesystem.squashfs:${LOWLIST}
-fi
-
-if [ -d /memory/images/changes-exit ]
-then
-	LOWLIST=/memory/images/changes-exit/$UDIR:${LOWLIST}
-	cp -a /memory/images/changes-exit/workdir/* $WORKDIR/. 2> /dev/null
-fi
-LOWLIST=`echo $LOWLIST | sed 's/:$//'`
-
-#echo "mount -t overlay -o upperdir=$UPPERDIR,lowerdir=$LOWLIST,workdir=$WORKDIR overlay /union"
-mount -t overlay -o upperdir=$UPPERDIR,lowerdir=$LOWLIST,workdir=$WORKDIR overlay /union
-if [ $? -ne 0 ]
-then
-	sh
+	echo "${i}${CYAN}Cannot read $NAME - corrupted module?${RST}"
+	rmdir /memory/images/"$NAME"
 fi
 }
 
@@ -412,7 +311,7 @@ fi
 if [ "$CHNEXIT" = EXIT ] || param changes-ro ; then
 	CHNEXIT=$CHNDEV/$LPTH; echo $CHNEXIT >/tmp/changes-exit
 	param changes-ro && echo "${i}${CYAN}changes will not be saved for this session${RST}" || echo "${i}${CYAN}changes will be saved only during reboot/shutdown${RST}"
-	setClean
+	clean_changes_dir
 	mkdir -p /memory/images/changes-exit
 	mount -o move /memory/changes /memory/images/changes-exit
 	umount /memory/changes 2>/dev/null;
@@ -428,7 +327,7 @@ elif [ $CHNEXIT = +EXIT ]; then
 		umount /memory/changes 2>/dev/null
 		rmdir $APTH/changes 2>/dev/null
 		mount -o loop /mnt/$DEV/$LPTH /memory/changes 2>/dev/null
-		setClean
+		clean_changes_dir
 		mkdir -p /memory/images/changes-exit
 		mount -o move /memory/changes /memory/images/changes-exit
 		rm -rf $APTH/tmp-changes 2> /dev/null
@@ -437,7 +336,7 @@ elif [ $CHNEXIT = +EXIT ]; then
 	else
 		echo "${i}${CYAN}option +EXIT is being used, changes are NOT written in memory${RST}"
 		echo "${i}${CYAN}temporary changes will be in /mnt/$DEV/$LPTH/tmp-changes ${RST}"
-		setClean
+		clean_changes_dir
 		mkdir -p /memory/images/changes-exit
 		mount -o move /memory/changes /memory/images/changes-exit
 		umount /memory/changes 2>/dev/null
diff --git a/trixie/rootcopy/opt/initramfs/linuxrc b/trixie/rootcopy/opt/initramfs/linuxrc
--- a/trixie/rootcopy/opt/initramfs/linuxrc
+++ b/trixie/rootcopy/opt/initramfs/linuxrc
@@ -28,7 +28,6 @@ clear
 echo "${BOLD}Starting init script.${RST}"
 
 # Variables:
-#CFG=`value cfgfile`; [ $CFG ] || CFG=initrd1.xz
 KERNEL=`uname -r`
 
 FOLDER=`value folder`
@@ -59,7 +58,6 @@ NVIDIA=`value nvidia`
 [ "$NVIDIA" = no -o "$NVIDIA" = none ] && NVIDIA=""
 
 livedbg=/var/log/livedbg
-LOGFILE=/var/log/boot.log
 
 ## Let's start!
 echo "${i}loading kernel modules..."
@@ -135,7 +133,11 @@ echo $DATADIR > /etc/homedrv
 
 debug
 
-# Setup changes:
+# Setup changes
+[ $PFULL ] && UDIR=filesystem || UDIR=upperdir
+UPPERDIR=/memory/changes/$UDIR
+WORKDIR=/memory/changes/workdir
+
 if [ $CHANGES ]; then
 	echo "${i}setting up directory for changes"
 	CHNEXIT=`echo $CHANGES | cut -d: -f1`
@@ -160,13 +162,11 @@ else
 	fail_chn
 fi
 
-if [ $PFULL ]; then
-mkdir -p /memory/changes/filesystem/mnt/live
-else
-mkdir -p /memory/changes/upperdir/mnt/live
-fi
-
 debug
+
+if [ $PFULL ] && [ -d /mnt/$DEV/"$LPTH"/pfull ]; then
+	NOLOAD="01-filesystem.squashfs|$NOLOAD"
+fi
 
 # Find base modules
 find $DATADIR -maxdepth 1 -name "*.squashfs" 2>/dev/null | egrep -ve "$NOLOAD" | sort >/tmp/modules
@@ -237,20 +237,69 @@ for EXTFOLDER in $EXTRAMOD; do
 done
 fi
 
-# Copy data to RAM:
+# Copy modules to RAM
 param copy2ram && TORAM=1
 param toram && TORAM=1
-if [ $TORAM ]; then echo "${i}copying data to RAM, this may take some time..."
-	if [ "$RAMMOD" ]; then
-	egrep -e "$RAMMOD" /tmp/modules > /tmp/rammod; cpmod /tmp/rammod
-	else cpmod /tmp/modules
-	fi
+if [ $TORAM ]; then
+    MODFILE=/tmp/modules # list of modules
+    [ "$RAMMOD" ] && { egrep -e "$RAMMOD" /tmp/modules > /tmp/rammod; MODFILE=/tmp/rammod; }
+    echo "${i}copying data to RAM, this may take some time..."
+    NUM=`grep -c '.' $MODFILE`
+    while read MODULE; do
+        echo -en "${YELLOW}  ($NUM modules left)  ${RST} \r"
+        let NUM=NUM-1
+        NAME="$(basename "$MODULE")"
+        cp "$MODULE" /memory/copy2ram 2>/dev/null
+        [ $? -eq 0 ] && { sed -i "s@^.*/$NAME@/memory/copy2ram/$NAME@" /tmp/modules; continue; }
+        rm /memory/copy2ram/"$NAME"
+        echo "${i}${CYAN}Cannot copy $NAME Other modules will be skipped${RST}"
+        #find /memory/copy2ram -name "*.kmodsfs" | sort >/tmp/modules
+        #find /memory/copy2ram -name "*.squashfs" | sort >>/tmp/modules
+        break
+    done < $MODFILE
+    echo -en "                       \r"
 fi
 
-#======================================
-# IncludeModules
-#--------------------------------------
-IncludeModules
+# Mount modules
+NUM=0
+echo "/memory/images/01-filesystem.squashfs" >/tmp/lowerdir
+MODULE="`grep -m1 '/01-filesystem.squashfs$' /tmp/modules`"
+if [ -n "$MODULE" ]; then
+	NAME="01-filesystem.squashfs"
+	mount_module # mount 01-filesystem.squashfs if existed
+else
+	mkdir -p /memory/images/"01-filesystem.squashfs"
+fi
+
+# Mount .kmodsfs kernel modules squashfs
+grep '.kmodsfs$' /tmp/modules | while read MODULE; do
+NAME="$(basename "${MODULE%.*}")" # remove extension .kmodsfs
+mount_module
+done
+
+# Mount other modules from list /tmp/modules
+grep -v '/01-filesystem.squashfs$' /tmp/modules | grep -v '.kmodsfs$' | while read MODULE; do
+NAME="$(basename "${MODULE%.*}" | tr -d ' ')" # remove extension .squashfs
+NAME="${NAME:0:14}" # truncate mountpoint name
+mount_module
+done
+
+clean_changes_dir
+if [ -d /memory/images/changes-exit ]; then
+	echo "/memory/images/changes-exit/$UDIR" >>/tmp/lowerdir
+	cp -a /memory/images/changes-exit/workdir/* $WORKDIR/. 2> /dev/null
+fi
+
+# Setup lowerdir list
+LOWLIST="`cat /tmp/lowerdir | tac`"
+LOWLIST="`echo $LOWLIST | sed 's/ /:/g'`"
+
+# Mount overlayfs
+mount -t overlay -o upperdir=$UPPERDIR,lowerdir=$LOWLIST,workdir=$WORKDIR overlay /union
+if [ $? -ne 0 ]; then
+	echo "${RED}ERROR Something went wrong. Press Ctrl+Alt+Del to reboot.${RST}"
+	sh
+fi
 
 debug
 
@@ -301,7 +350,6 @@ debug
 
 # Remove /union/mnt/XX dir's
 for x in `ls -1 /union/mnt | grep -v live`; do
-#	echo $x
 	[ -d /union/mnt/$x ] && rmdir /union/mnt/$x # Will fail if dir not empty!
 	[ -L /union/mnt/$x ] && rm -f /union/mnt/$x
 done
