Update formatting and description in build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -10,19 +10,18 @@
 
 # Modified by gumanzoy <gumanzoy@gmail.com>
 # https://github.com/PocketHandyBox/phb-base
-# https://forum.puppylinux.com/viewtopic.php?p=88473
+# https://forum.puppylinux.com/viewtopic.php?t=13647
 
 export LD_LIBRARY_PATH=
 
 if [ "`whoami`" != "root" ]; then
-echo "This script should be run as root"
-sleep 3
-exit
+	echo "This script should be run as root"
+	sleep 3 && exit
 fi
 
 # This makes sure when the script is interrupted, that all mount 'binds' will unmount 
 exitfn () {
-    trap SIGINT              # Resore signal handling for SIGINT
+trap SIGINT              # Resore signal handling for SIGINT
 echo -e "\e[0;36mUnmounting mount binds in chroot\033[0m"
 #umount -l chroot/tmp
 umount -l $LAUNCHDIR/bookworm/chroot/proc 2> /dev/null
@@ -32,16 +31,15 @@ umount -l $LAUNCHDIR/bookworm/chroot/dev 2> /dev/null
 
 [ ! -d $LAUNCHDIR/bookworm/apt ] && mv -f $LAUNCHDIR/bookworm/chroot/var/cache/apt $LAUNCHDIR/bookworm/
 rm -f $LAUNCHDIR/bookworm/apt/archives/lock 2> /dev/null
-   sleep 2
-   if mountpoint -q $LAUNCHDIR/bookworm/chroot/dev; then     # just in case check dev
-   echo -e "\e[0;31mSomething went wrong, directory chroot cannot be removed\033[0m"
-   echo -e "\e[0;31mMake sure it's not in use by some process and try again, exiting...\033[0m"
-   sleep 2
-   exit
-   else
-   rm -rf $LAUNCHDIR/bookworm/chroot
-   rm -f $LAUNCHDIR/bookworm/*.conf 2> /dev/null
-   fi
+sleep 2
+if mountpoint -q $LAUNCHDIR/bookworm/chroot/dev; then     # just in case check dev
+	echo -e "\e[0;31mSomething went wrong, directory chroot cannot be removed\033[0m"
+	echo -e "\e[0;31mMake sure it's not in use by some process and try again, exiting...\033[0m"
+	sleep 2 && exit
+else
+	rm -rf $LAUNCHDIR/bookworm/chroot
+	rm -f $LAUNCHDIR/bookworm/*.conf 2> /dev/null
+fi
 exit
 }
 export -f exitfn
@@ -62,37 +60,18 @@ export LAUNCHDIR="$PWD"
 
 ########### Options (configuration)  ###########
 
-helptext="build 01-filesystem.squashfs for Debian Bookworm (Debian 12)\n
-usage: $(basename $0) <config_file>\n
-	-help show this help\n
-	Example using custom config file: \n
-	build mycustom.conf \n"
-
-params=$@
-	
-if [ ${#params} -eq 0 ]; then	# no options, so print info/help...
-	echo -e $helptext
-	exit
+if [ -f "$1" ]; then
+	config="$1"
+	. "$config"
+else exit
 fi
 
-arg=$1
-		case $arg in
-		-help|--help)
-echo -e $helptext
-exit
-			;;
-		*.conf) # ● fredx181, first arg needs to have .conf extension
-config=$1
-	. $config
-	CONFIG="yes"
-			;;
-
-		*)
-echo -e "\e[0;31mNot a valid option\033[0m"
-echo -e $helptext
-exit
-			;;
-		esac
+if [ -z "$PL_BASE" ] || [ -z "$INSTALL" ]; then
+	echo -e "\e[0;31mThis config file cannot be used, sorry, exiting...\033[0m"
+	exit
+else
+	echo -e "\e[0;36mRunning with configuration: \e[1;29m$(readlink -f $config)\e[0;29m\033[0m"
+fi
 
 # export final variables defined from custom .conf file
 export SYSTEMD="$SYSTEMD"
@@ -110,89 +89,57 @@ else
 fi
 
 if [ "$(uname -m)" = "i686" ]; then
-echo
-echo -e "\e[0;32mOK, running 32-bit OS, building live system for 32-bit: $(uname -m)\033[0m"
-export ARCH="i386"
-elif [ "$(uname -m)" = "x86_64" ]; then
-echo
-	if [ "$BUILD686" = "TRUE" ]; then
-	echo -e "\e[0;32mOK, running 64-bit OS, building live system for 32-bit: i686\033[0m"
+	echo -e "\e[0;32mOK, running 32-bit OS, building live system for 32-bit: $(uname -m)\033[0m"
 	export ARCH="i386"
+elif [ "$(uname -m)" = "x86_64" ]; then
+	if [ "$BUILD686" = "TRUE" ]; then
+		echo -e "\e[0;32mOK, running 64-bit OS, building live system for 32-bit: i686\033[0m"
+		export ARCH="i386"
 	else
-	echo -e "\e[0;32mOK, running 64-bit OS, building live system for 64-bit: $(uname -m)\033[0m"
-	export ARCH="amd64"
+		echo -e "\e[0;32mOK, running 64-bit OS, building live system for 64-bit: $(uname -m)\033[0m"
+		export ARCH="amd64"
 	fi
 fi
 
-echo -e "\e[0;33mCreate a Debian Bookworm minimal live system similar to 'DebianDog'\nWith overlay support and porteus-boot style included\n\nIt's required to have at least 3 GB free space\nand to run this script on a Linux filesystem, e.g. ext4\033[0m"
+echo -e "\e[0;33mBuild Debian Bookworm (Debian 12) base filesystem '01-filesystem.squashfs' for 'PocketHandyBox'\nWith overlay support and porteus-boot style included\n\nIt's required to have at least 3 GB free space\nand to run this script on a Linux filesystem, e.g. ext4\033[0m"
 echo -e "\e[0;32mBuilding will be done in: $PWD/bookworm\033[0m"
-if [ "$CONFIG" = "yes" ]; then
-	if [ -z "$PL_BASE" ] || [ -z "$INSTALL" ]; then
-	echo -e "\e[0;31mThis config file cannot be used, sorry, exiting...\033[0m"
-	exit
-	else
-echo -e "\e[0;36mRunning with configuration: \e[1;29m$(readlink -f $config)\e[0;29m\033[0m"
-	fi
-else
-echo -e "\e[0;36mNo custom config in use\033[0m"
-echo -e "\e[0;36mUsing standard configuration defined on top of script\033[0m"
-fi
+
 #echo -e "\e[0;32mIf you'd like a log from the output, run again e.g:\033[0m"
 #echo -e "\e[0;33m$0 -gui 2>&1 | tee build.log\033[0m"
-echo -e "\e[0;36mFirst setting up debootstrap, this will take a few minutes\nAfter that you will be asked to set the password for 'root'\033[0m"
-echo
+echo -e "\e[0;36mFirst setting up debootstrap, this will take a few minutes\033[0m"
 
 if [ -d "bookworm/chroot" ]; then 
-echo -e "\e[0;33m Working directory 'bookworm' already exists \n To be able to continue, contents need to be removed first\n All files in bookworm will be deleted, except the apt cache in chroot\033[0m"
-#read -p "Are you sure to delete contents of directory bookworm? (Enter=yes) (Y/n)?" choice
-choice=y
+	echo -e "\e[0;33m Working directory 'bookworm' already exists\n All files in bookworm will be deleted, except the apt cache in chroot\033[0m"
+	echo -e "\e[0;36mUnmount mount binds and remove bookworm/chroot...\033[0m"
+	#umount -l chroot/tmp
+	umount -l bookworm/chroot/proc 2> /dev/null
+	umount -l bookworm/chroot/sys 2> /dev/null
+	umount -l bookworm/chroot/dev/pts 2> /dev/null
+	umount -l bookworm/chroot/dev 2> /dev/null
 
-case "$choice" in 
-  y|Y|"")
-
-echo -e "\e[0;36mUnmount mount binds and remove bookworm/chroot...\033[0m"
-#umount -l chroot/tmp
-umount -l bookworm/chroot/proc 2> /dev/null
-umount -l bookworm/chroot/sys 2> /dev/null
-umount -l bookworm/chroot/dev/pts 2> /dev/null
-umount -l bookworm/chroot/dev 2> /dev/null
-
-mv bookworm/chroot/var/cache/apt bookworm/ 2> /dev/null
-   if mountpoint -q bookworm/chroot/dev; then      # just in case check dev
-   echo -e "\e[0;31mSomething went wrong, directory bookworm/chroot cannot be removed\033[0m"
-   echo -e "\e[0;31mMake sure it's not in use by some process and try again, exiting...\033[0m"
-   sleep 2
-   exit
-   else
-   rm -rf bookworm/chroot
-   fi
-mkdir -p bookworm/chroot/var/cache 2> /dev/null
-mv bookworm/apt bookworm/chroot/var/cache/ 2> /dev/null
-rm -f bookworm/*.conf 2> /dev/null
-#find bookworm -mindepth 1 ! -wholename 'bookworm/chroot/*' -delete 2> /dev/null
-echo -e "\e[0;32mOK, continue...\033[0m"
-;;
-  n|N)
-echo "Exiting..."
-sleep 3
-exit 0
-;;
-*)
-echo -e "\e[0;31mNot a valid choice, exiting....\033[0m"
-sleep 3
-exit 0
-;;
-esac
+	mv bookworm/chroot/var/cache/apt bookworm/ 2> /dev/null
+	if mountpoint -q bookworm/chroot/dev; then      # just in case check dev
+		echo -e "\e[0;31mSomething went wrong, directory bookworm/chroot cannot be removed\033[0m"
+		echo -e "\e[0;31mMake sure it's not in use by some process and try again, exiting...\033[0m"
+		sleep 2 && exit
+	else
+		rm -rf bookworm/chroot
+	fi
+	mkdir -p bookworm/chroot/var/cache 2> /dev/null
+	mv bookworm/apt bookworm/chroot/var/cache/ 2> /dev/null
+	rm -f bookworm/*.conf 2> /dev/null
+	#find bookworm -mindepth 1 ! -wholename 'bookworm/chroot/*' -delete 2> /dev/null
+	echo -e "\e[0;32mOK, continue...\033[0m"
 fi
 
 sleep 3
 
 if [ $(command -v apt-get 2>/dev/null) ];then
- echo -e "\e[0;36mUpdate the package lists...\033[0m"
- apt-get update
- echo -e "\e[0;36mInstall some required packages, e.g. xz-utils, wget, squashfs-tools, etc...\033[0m"
- apt-get install debootstrap squashfs-tools wget xz-utils zstd -y
- ok_or_failed
+	echo -e "\e[0;36mUpdate the package lists...\033[0m"
+	apt-get update
+	echo -e "\e[0;36mInstall some required packages, e.g. xz-utils, wget, squashfs-tools, etc...\033[0m"
+	apt-get install debootstrap squashfs-tools wget xz-utils zstd -y
+	ok_or_failed
 fi
 
 if [ -z `which debootstrap` ] || [ ! -e /usr/share/debootstrap/scripts/bookworm ]; then
@@ -209,9 +156,9 @@ debootstrap --arch=$ARCH --variant=minbase --include=apt-transport-https,ca-cert
 ret=$?
 echo $ret
 if [ $ret -ne 0 ]; then
-echo -e "\e[0;31mFailed to install the base system\033[0m"
-echo -e "\e[0;32mThis can happen sometimes, please try again, exiting now...\033[0m"
-exit
+	echo -e "\e[0;31mFailed to install the base system\033[0m"
+	echo -e "\e[0;32mThis can happen sometimes, please try again, exiting now...\033[0m"
+	exit
 fi
 
 # Cleaning after debootstrap
@@ -269,10 +216,10 @@ echo "Acquire::Check-Valid-Until "0";" >> /etc/apt/apt.conf
 #fi
 
 if [ "$SYSTEMD" = "FALSE" ]; then
-PL_SYS=$PL_SYSV
+	PL_SYS=$PL_SYSV
 elif [ "$SYSTEMD" = "TRUE" ]; then
-rm -f /etc/apt/preferences.d/00systemd /etc/apt/sources.list.d/devuan.sources /usr/share/keyrings/devuan-archive-keyring.gpg
-PL_SYS=$PL_SYSTEMD
+	rm -f /etc/apt/preferences.d/00systemd /etc/apt/sources.list.d/devuan.sources /usr/share/keyrings/devuan-archive-keyring.gpg
+	PL_SYS=$PL_SYSTEMD
 fi
 
 # Add DogLinux github repo
@@ -288,8 +235,8 @@ echo -e "\e[0;36mPlease set the password for 'root'\033[0m"
 echo -e "\e[0;33mAlso now you may want to add to or edit files in bookworm/chroot\033[0m" 
 #passwd root
 if [ $? -ne 0 ]; then # try again if passwords not match
-echo -e "\e[0;36mPlease try again, type password for root\033[0m"
-#passwd root
+	echo -e "\e[0;36mPlease try again, type password for root\033[0m"
+	#passwd root
 fi
 [ $? -ne 0 ] && echo -e "\e[0;31mWarning: password is not set\033[0m"; sleep 3
 
@@ -300,8 +247,8 @@ echo
 echo -e "\e[0;36mPlease set the password for user 'puppy'\033[0m"
 #passwd puppy
 if [ $? -ne 0 ]; then # try again if passwords not match
-echo -e "\e[0;36mPlease try again, type password for puppy\033[0m"
-#passwd puppy
+	echo -e "\e[0;36mPlease try again, type password for puppy\033[0m"
+	#passwd puppy
 fi
 [ $? -ne 0 ] && echo -e "\e[0;31mWarning: password is not set\033[0m"; sleep 3
 echo
@@ -356,27 +303,22 @@ mkdir -p /opt/bin
 
 # simulate install first to check for errors, if there are, exit
 echo -e "\e[0;36mChecking packages . . .\033[0m"
-sleep 3
 apt-get install -s -y $INSTALL
 ret=$?
 if [ $ret -eq 100 ]; then
-echo -e "\e[0;31mSorry, there are one or more errors, see above.\033[0m"
-echo -e "\e[0;31mCould be a typo in a package name.\033[0m"
-echo -e "\e[0;36mExiting . . .\033[0m"
-touch /exit_
-sleep 3
-exit
+	echo -e "\e[0;31mSorry, there are one or more errors, see above.\033[0m"
+	echo -e "\e[0;31mCould be a typo in a package name.\033[0m"
+	echo -e "\e[0;36mExiting . . .\033[0m"
+	touch /exit_
+	exit
 else
-echo -e "\e[0;32mAll packages checked OK, continue now to install some basic packages... \033[0m"
-sleep 3
+	echo -e "\e[0;32mAll packages checked OK, continue now to install some basic packages... \033[0m"
 fi
 
 ############ Start installing packages ############
 
 ####### Start installing packages, as defined in configuration #######
 echo -e "\e[0;36mInstall packages, as defined in configuration\033[0m"
-
-sleep 3
 
 ### Do the real installing
 DEBIAN_FRONTEND=noninteractive apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y $INSTALL
@@ -443,7 +385,6 @@ uncompress_files usr/share/man
 # remove broken links
 # $1 = search directory
 remove_broken_links() {
-#find "$1" -type l -exec test ! -e {} \; -print | xargs rm -vf
 find "$1" -xtype l -delete 2> /dev/null
 }
 
@@ -583,22 +524,16 @@ if [ -n "$TEMPMIRROR" ]; then
 	sed -i s/"$TEMPMIRROR"/deb.debian.org/ chroot/etc/apt/sources.list.d/debian.sources
 fi
 
-mkdir -p apt/archives
-mv -f chroot/var/cache/apt/archives/*.deb ./apt/archives/
-
 if [ "$(cat chroot/etc/X11/default-display-manager 2> /dev/null)" ]; then
-echo -e "\e[0;36mIt looks like you have a display-manager installed\033[0m"
-cat chroot/etc/X11/default-display-manager
-echo -e "\e[0;36mThis probably will conflict with the default login method (through /etc/inittab)\033[0m"
-cp -af chroot/etc/inittab-noauto chroot/etc/inittab
-
-if [ "$SYSTEMD" = "TRUE" ]; then
-rm -f chroot/etc/systemd/system/graphical.target.wants/getty@tty1.service
-rm -f chroot/etc/systemd/system/getty.target.wants/getty@tty1.service
-fi
-
-echo -e "\e[0;32mDisabled autologin, using display-manager for login\033[0m"
-sleep 3
+	echo -e "\e[0;36mIt looks like you have a display-manager installed\033[0m"
+	cat chroot/etc/X11/default-display-manager
+	echo -e "\e[0;36mThis probably will conflict with the default login method (through /etc/inittab)\033[0m"
+	cp -af chroot/etc/inittab-noauto chroot/etc/inittab
+	if [ "$SYSTEMD" = "TRUE" ]; then
+		rm -f chroot/etc/systemd/system/graphical.target.wants/getty@tty1.service
+		rm -f chroot/etc/systemd/system/getty.target.wants/getty@tty1.service
+	fi
+	echo -e "\e[0;32mDisabled autologin, using display-manager for login\033[0m"
 fi
 
 # Download extra squashfs modules if DE config is set
@@ -608,8 +543,10 @@ fi
 
 #update-icon-caches chroot/usr/share/icons/hicolor/
 
-mkdir -p "$ARCH" 2> /dev/null
+mkdir -p apt/archives
+mv -f chroot/var/cache/apt/archives/*.deb ./apt/archives/
 
+mkdir -p "$ARCH" 2> /dev/null
 echo -e "\e[0;33mNow we will create: filesystem: '01-filesystem.squashfs'"
 mksquashfs chroot "$ARCH"/01-filesystem.squashfs -b 512k $MKSFSCMP
 ok_or_failed
@@ -621,4 +558,3 @@ rm -rf apt 2> /dev/null
 echo -e "\e[0;32mFinished! If all went well, '01-filesystem.squashfs' file are in ""$ARCH"" folder \n\nHave a good day!\033[0m"
 
 exit 0
-
