Merge save2flash snap-ex snapmergepuppy into one script

diff --git a/trixie/rootcopy/usr/local/bin/save2flash b/trixie/rootcopy/usr/local/bin/save2flash
--- a/trixie/rootcopy/usr/local/bin/save2flash
+++ b/trixie/rootcopy/usr/local/bin/save2flash
@@ -1,10 +1,12 @@
 #!/bin/bash
 
-# save2flash save changes in the middle of a session, or at shutdown
-# In case of changes=EXIT:/ is specifiied on kernel boot command line
-# Written/modified by fredx181
+# save2flash save changes in the middle of a session, or at shutdown/reboot
+# In case of 'makepfile' is used or changes=EXIT:/ is specifiied on kernel boot command line
+# by gumanzoy https://github.com/PocketHandyBox
 
-# Modified by gumanzoy https://github.com/PocketHandyBox
+# Use code from 'save2flash', 'snap-ex', 'snapmergepuppy' by fredx181
+# https://github.com/doglinux/bookworm/raw/master/amd64/porteusbootscripts_1.2.0_all.deb
+
 # Deprecated gtkdialog-splash replaced by notify-send (libnotify-bin package required)
 # Xdialog replaced by yad
 
@@ -14,9 +16,25 @@ if [ "`whoami`" != "root" ]; then
 	exit 1
 fi
 
+# Export some color functions
+RED=`echo -e '\e[1;31m'`
+GREEN=`echo -e '\e[1;32m'`
+YELLOW=`echo -e '\e[1;33m'`
+BLUE=`echo -e '\e[1;34m'`
+PURPLE=`echo -e '\e[1;35m'`
+CYAN=`echo -e '\e[1;36m'`
+BOLD=`echo -e '\e[1m'`
+RST=`echo -e '\e[0m'` # Reset Color
+
+[ "$DISPLAY" ] && GUI=1
+
 PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
 
-sfsunloadfn() {
+SNAP="/mnt/live/memory/changes"
+[ -d "$SNAP"/filesystem ] && UDIR=filesystem || UDIR=upperdir
+BASE="/mnt/live/memory/images/changes-exit"
+
+sfsunload_ask_fn() {
 if [ -f /mnt/live/tmp/modules ]; then
 CHNGS=/mnt/live/memory/images/SFS  # porteus-boot
 else
@@ -26,76 +44,132 @@ fi
 if [ "$(ls $CHNGS 2> /dev/null)" ]; then
 yad --title="Save Session" --window-icon=document-save --center --fixed \
  --text="Required is to unload modules that were manually loaded,\notherwise your changes will include broken symlinks.\n\nContinue ?"
-[ $? -ne 0 ] && exit
-sfsunload
+[ $? -ne 0 ] && exit 1
 fi
 }
 
-save2flashfn() {
-RAMUSED=$(du -cs --apparent-size /mnt/live/memory/changes | awk 'END {print $1}')
-
-SAVEFREE=$(df -k /mnt/live/memory/images/changes-exit | tr -s ' ' | cut -f 4 -d ' ' | tail -1)
-
-RAMUSEDMB=$(du -chs --apparent-size /mnt/live/memory/changes | awk 'END {print $1}')
-echo -e "Not saved yet session data: ""\e[0;32m""${RAMUSEDMB}""\e[0m"
-
-SAVEFREEMB=$(df -m /mnt/live/memory/images/changes-exit | tr -s ' ' | cut -f 4 -d ' ' | tail -1)
-echo -e "Your save file/folder has free space: ""\e[0;34m""${SAVEFREEMB}MB""\e[0m"
-
-if [ "$SAVEFREE" -gt "$RAMUSED" ]; then
-notify-send --app-name=save2flash --icon=document-save "Saving session" \
-"Session data to save: ${RAMUSEDMB}\nFree space in save storage: ${SAVEFREEMB}MB"
-snapmergepuppy 2> /dev/null
-
-#rm -fr /mnt/live/memory/images/changes-exit/$UPPER/run
-#rm -f /mnt/live/memory/images/changes-exit/$UPPER/etc/blkid-cache
-#rm -f /mnt/live/memory/images/changes-exit/$UPPER/etc/udev/rules.d/70-persistent-net.rules
-#sleep 2
-# next commented out now, already done in snapmergepuppy
-#mount -no remount,add:1:/mnt/live/memory/images/changes-exit=ro+wh aufs /
-#chmod a=rwx,o+t /mnt/live/memory/images/changes-exit/tmp 2> /dev/null
-#sleep 2
-#kill $!
-
+changes_ask_fn() {
+TEXT="Save Changes?
+Your session will be saved in 10 seconds
+Press Enter to save session"
+sleep 0.2
+if [ -z `which dialog` ]; then
+    echo "${PURPLE}Save Changes?${RST} Press ${BOLD}Enter or Space${RST} to save or ${BOLD}any other key${RST} to ${RED}cancel${RST}"
+    NUM=10
+    while [ $NUM -gt 0 ]; do
+        echo -en "Your session will be saved in${YELLOW} $NUM ${RST}seconds \r"
+        read -s -t1 -n1 ANS && break || let NUM=NUM-1
+    done
+    echo -en "                       \r"
+    [ "$ANS" = "" ] && return 0
 else
-echo -e "\e[0;31m""No save can be done, ${SAVEFREEMB}MB is not enough available space.""\e[0m"
-TEXT="Sorry, not enough space available in savefile (or folder)
-No saving has been done
-Session data to copy: ${RAMUSEDMB}
-Available free space in save file/folder: ${SAVEFREEMB}MB"
-yad --title="Save Session" --text="$TEXT" --window-icon=document-save --center --fixed --button=Close\!gtk-close
-exit 1
+    dialog --timeout 10 --yes-label "Save" --no-label "Not save" --yesno "$TEXT" 0 0 >/dev/console
+    [ $? -eq 1 ] || return 0
 fi
+echo "${RED}Session not saved!                       ${RST}"
+exit 0
 }
 
-if grep -q pfull= /proc/cmdline; then
-UPPER=filesystem
-else
-UPPER=upperdir
+if [ $GUI ] && [ ! -f /tmp/savefile.txt ] && [ ! -f /mnt/live/tmp/changes-exit ]; then
+yad --title="Save Session" --window-icon=document-save --center --fixed --button=Close\!gtk-close \
+ --text="Not booted with the 'changes=EXIT:/' option"
+exit 0
 fi
 
-SAVEFILE_MNT="/mnt/live/memory/images/changes-exit"
+if [ -f /mnt/live/tmp/sessionsaved ]; then
+echo "${GREEN}Session saved${RST}"
+exit 0
+fi
+
+if [ -f /mnt/live/tmp/changesx ]; then
+echo "${BOLD}Session not saved${RST}"
+exit 0
+fi
+
+if [ ! -f /tmp/savefile.txt ] && [ ! -f /mnt/live/tmp/changes-exit ]; then
+    if [ -f /mnt/live/etc/nochanges ]; then echo "${BOLD}Session not saved${RST}"
+    else echo "${GREEN}Session already saved (using overlay)${RST}"
+    fi
+    exit 0
+fi
 
 if [ -f /tmp/savefile.txt ] && [ -f /mnt/live/etc/nochanges ]; then
-	. /tmp/savefile.txt
-	if [ ! -d $SAVEFILE_MNT ] ; then
-	mkdir $SAVEFILE_MNT
-	fi
-
-	if [ ! -d $SAVEFILE ] ; then
-	mount $SAVEFILE $SAVEFILE_MNT
-	else
-	mount --bind $SAVEFILE $SAVEFILE_MNT
-	fi
-
-	sfsunloadfn
-	save2flashfn
-
-elif [ -f /mnt/live/tmp/changes-exit ]; then
-	sfsunloadfn
-	save2flashfn
-
-else
-	yad --title="Save Session" --window-icon=document-save --center --fixed --button=Close\!gtk-close \
-	--text="Not booted with the 'changes=EXIT:/' option"
+    . /tmp/savefile.txt
+    [ -d "$BASE" ] || mkdir -p "$BASE"
+    if [ ! -d $SAVEFILE ]; then
+        mount -o loop "$SAVEFILE" "$BASE"
+    else
+        mount -o bind "$SAVEFILE" "$BASE"
+    fi
+    if [ $? -ne 0 ]; then
+        echo "${RED}Session not saved!${RST} Failed to mount changes${BOLD} $SAVEFILE ${RST}"
+        exit 1
+    fi
+    [ -d "$BASE/$UDIR" ] || mkdir -p "$BASE/$UDIR"
+    rm -f /mnt/live/etc/nochanges 2>/dev/null
 fi
+
+if [ -z "$GUI" ] && [ ! -f /tmp/savefile.txt ]; then
+    changes_ask_fn
+fi
+
+[ $GUI ] && sfsunload_ask_fn
+sfsunload
+
+RAMUSED=$(du -cs --apparent-size "$SNAP" | tail -1 | cut -f1)
+SAVEFREE=$(df -k --output=avail "$BASE" | tail -1 | tr -d ' ')
+RAMUSEDMB=$(du -chs --apparent-size "$SNAP" | tail -1 | cut -f1)
+SAVEFREEMB=$(df -m --output=avail "$BASE" | tail -1 | tr -d ' ')
+
+TEXT="Sorry, not enough space available in savefile (or folder)
+No saving has been done
+Session data to copy: <b>${RAMUSEDMB}</b>
+Available free space in save file/folder: <b>${SAVEFREEMB}MB</b>"
+
+if [ "$SAVEFREE" -lt "$RAMUSED" ]; then
+    echo "${RED}Session not saved! ${BOLD}Session data to copy: ${BLUE}${RAMUSEDMB}${RST}"
+    echo "${BOLD}Not enough free space in save file/folder: ${BLUE}${SAVEFREEMB}MB${RST}"
+    [ $GUI ] && yad --title="Save Session" --text="$TEXT" --window-icon=document-save --center --fixed --button=Close\!gtk-close
+    exit 1
+fi
+
+echo "${GREEN}Saving session...                       ${RST}"
+[ $GUI ] && notify-send --app-name=save2flash --icon=document-save "Saving session" \
+"Session data to copy: ${RAMUSEDMB}\nFree space in save file/folder: ${SAVEFREEMB}MB"
+
+touch /mnt/live/tmp/changes-exit
+FILESAVELIST="/mnt/live/tmp/filesave$RANDOM"
+FILERMLIST="/mnt/live/tmp/filerm$RANDOM"
+
+find "$SNAP/$UDIR"/* | sed "s@$SNAP/$UDIR/@@" | egrep -v '^tmp|^run|^mnt' | while read LINE; do
+    # check for "mask" files in $SNAP
+    if [ -c "$SNAP/$UDIR/$LINE" ] && [ ! -s "$SNAP/$UDIR/$LINE" ]; then
+        # scan base .squashfs's in /mnt/live/memory/images/ 
+        for MOD in $(ls /mnt/live/memory/images/ | egrep -vx 'changes-exit|SFS'); do
+            # check if exist in base .squashfs's
+            if [ -e "/mnt/live/memory/images/$MOD/$LINE" ] || [ -L "/mnt/live/memory/images/$MOD/$LINE" ]; then
+                # send "mask" files to list to be copied later
+                echo "$LINE" >> "$FILESAVELIST"
+                break
+            fi
+        done
+    else
+        # send "regular" files to list to be copied later
+        echo "$LINE" >> "$FILESAVELIST"
+    fi
+done
+
+find "$BASE/$UDIR"/* -type l -o -type f -o -type d 2>/dev/null | sed "s@$BASE/$UDIR@@" | while read LINE; do
+    if [ ! -e "$LINE" ] && [ ! -L "$LINE" ]; then
+        echo "$BASE/$UDIR/$LINE" >> "$FILERMLIST"
+    fi
+done
+
+# remove files from $FILERMLIST from $BASE
+[ -f "$FILERMLIST" ] && xargs -d '\n' -a "$FILERMLIST" rm -rf
+# copy from $FILESAVELIST to $BASE
+[ -f "$FILESAVELIST" ] && rsync -a --files-from="$FILESAVELIST" "$SNAP/$UDIR" "$BASE/$UDIR" 2>/dev/null
+
+sync
+rm -f "$FILESAVELIST" "$FILERMLIST"
+exit 0
